### ISSUE TITLE
Backport to 1.20.1?

### ISSUE THREAD

**Issue by vivifalls** [DriHut/ReFramed#2]
Are there any plans to backport this mod to 1.20.1? Seems like a weird decision to lock it to .4 since most mods for 1.20 are in the .1 version. I know mod development takes time and things are easier said than done but would be nice knowing if any backporting is planned, if not, that's fine too

**Comment by DriHut** [comment]
Hi. I looked back at what I needed to do to update from 1.20.1 and all things considered it could be done without too much efforts. Though the mod is still under development as I need to add some more features and shapes so back porting it is not my priority. Though when the mod will have reached a more polished state I will then maybe consider it more seriously. (Also keep in mind that if the mod is not planned to be updated to other versions of the game is due to the fact that I'm making it for a personal project which is meant to stay in 1.20.4 and in which I need to develop some more things unrelated to this mod).
Also if you are a developer and want to do it you can always make it and make a push request i will then add it mentioning that you did the back port.
Feel free to ask if you have some more questions / suggestions.

**Comment by DriHut** [comment]
Someone did it and seems like it wasn't too hard. Anyway you should thanks [RemagOfficial](https://github.com/RemagOfficial) for taking the initiative ^^.
