### ISSUE TITLE
Crash when working with framedblocks

### ISSUE THREAD

**Issue by IJuanTM** [DriHut/ReFramed#9]
When working with framedblocks I keep getting crashes from Indium saying "Tessellating block in world - Indium Renderer"

Here is the full crashlog: https://mclo.gs/74pUVRA

And the latest.log as well: https://mclo.gs/dgI4LIl

Any idea if this is fixable? I saw a lot of people online saying to disable Continuity, but I already have since the framedblocks are invisible with Continuity installed.

Thanks!

**Comment by DriHut** [comment]
Ok so from what I see it is indeed Reframed causing the crash but does your modpack even run correctly without it? The logs are filled with errors from other mods. Second question does this happen at the loading of the world or only after some time ?  If this is the case this issue will be fixed in the upcomming version this is due to the way I handled caching before and I noticed such an issue and so modified the way it works. Although I need to understand how to make multiversion mods as the latest version is currently only under mc 1.20.4.

**Comment by IJuanTM** [comment]
Yeah the mod pack runs fine with and without. It is true that it has a lot of errors and warnings though, no idea what causes them, seem to be mostly issues with the code of the mods themselves, not conflicts per se. 

The crashes happens at random, but always when placing a framedblock or filling it in, or interacting with it in some other way. Sometimes it happens at the first one I place after loading into the world, other times I can place like 50 of them before it happens.

Hopefully it can get fixed, but unfortunately for me it is not possible to upgrade above 1.20.1 for me, as a lot of mods I have aren't supported for later versions.

**Comment by DriHut** [comment]
Ok so that confirms the source of the issue and it has already been addressed as mentioned above. As for it coming to the 1.20.1 branch I will keep it up to date unless it requires to many complicated changes but from what I've seen it should be alright meaning you can expect the 1.20.1 version to be released the same day.

Next version requires still some more work as I want to add some more blocks to increase the palette of available shapes. That said since this issue is present I will try to make a sub version with what I currently have.

**Comment by DriHut** [comment]
I've published a newer version if you want to try it out to make sure the issue won't happen again

**Comment by IJuanTM** [comment]
Alright great! Trying it out now, no crashes yet O_O. Did notice that the the "Slabs Cube Frame" block facing south has flipped around. So the texture face towards the south now faces north and the other way around.

**Comment by DriHut** [comment]
Yeah The way I was doing it before was incoherent as now the first theme is on the negative direction of the axis and the second on the positive one so this is the same for the shapes that had this the other way around on that axis. Meaning I won't be changing that and is now a simpler way for me to orient everything.

**Comment by IJuanTM** [comment]
Ah okay, makes sense! I have been playing for half an hour now and haven't gotten any crashes, so I think it has been fixed! Thanks very much for the quick update!
